name: Create Build Artifacts

env:
  CI: true

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2.1.4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'

      - run: yarn --frozen-lockfile

      - name: Bump package.json
        run: |
          npm --no-git-tag-version version $(npm show . version)-beta.dangerous.$(git rev-parse --short HEAD)

      - run: yarn tsc && yarn lint
      - run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: |
            *
            !src
            !.husky
            !.github
            !.git
            !node_modules
